var cameras =
[{ "title": "React - The Complete Guide (incl Hooks, React Router, Redux)",
"price": 9.99,
"author":"Dr. Moorish Kith",
"img":"https://colorlib.com/wp/wp-content/uploads/sites/2/react-dev-tools-logo.jpg"},
{ "title": "React Native - The Practical Guide [2020 Edition])",
"price": 19.99,
"author":"Dr. Jeff Bejosh",
"img":"https://www.webrexstudio.com/wp-content/uploads/2019/05/react-js-image.png"},
{ "title": "The Complete React Native + Hooks Course [2020 Edition])",
"price": 39.99,
"author":"Mark Tawin",
"img":"https://www.mediaan.com/wp-content/uploads/2019/08/flutter-vs-react-native-1200x675.jpg"},
{"title": "The Complete JavaScript Course 2020: Build Real Projects!",

"price": 9.99,
"author":"Jonas Schmedtmann",
"img":"https://cdn.mos.cms.futurecdn.net/EzgdmaCQuT84bgDL4fhXZS.jpg"},
{ "title": "The Complete 2020 Web Development Bootcamp",
"price": 19.99,
"author":"Dr. Angela Yu",
"img":"https://www.webrexstudio.com/wp-content/uploads/2019/05/react-js-image.png"},
{ "title": "Node.js, Express, MongoDB & More: The Complete Bootcamp 2020",
"price": 69.99,
"author":"Mr Alex Haul",
"img":"https://cdn.evilmartians.com/front/posts/optimizing-react-virtual-dom-explained/cover-a1d5b40.png"},
{ "title": "JavaScript: Understanding the Weird Parts",
"price": 9.99,
"author":"Dr. Jasim ",
"img":"https://www.monterail.com/hubfs/vuevsreact.jpg"},
{ "title": "JavaScript Algorithms and Data Structures Masterclass",
"price": 19.99,
"author":"Atm Alim",
"img":"http://crowdforthink.com/assets/uploads/blogs/6ec3fae84857a1f5dc59eebcc6c0775e.png"},
{ "title": "JavaScript: The Advanced Concepts",
"price": 9.99,
"author":"Lord Karnawalis",
"img":"https://cdn.evilmartians.com/front/posts/optimizing-react-virtual-dom-explained/cover-a1d5b40.png"},
{ "title": "MERN Stack Front To Back: Full Stack React, Redux & Node.js",
"price": 29.99,
"author":"David Villa",
"img":"https://res.cloudinary.com/indepth-dev/image/fetch/w_1000,f_auto/https://admin.indepth.dev/content/images/2019/07/react-fiber.png"},
{ "title": "React Native - The Practical Guide [2020 Edition])",
"price": 19.99,
"author":"Leonel Messi",
"img":"https://www.freecodecamp.org/news/content/images/size/w2000/2020/03/cover-3.png"},
{ "title": "MERN Stack Front To Back: Full Stack React, Redux & Node.js",
"price": 9.99,
"author":"Christiano Ronaldo",
"img":"https://cdn.evilmartians.com/front/posts/optimizing-react-virtual-dom-explained/cover-a1d5b40.png"}
];

export default cameras;